### ISSUE TITLE
Run non-Django unit tests from test workflow

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/.github#165]
Make sure that non-Django unit tests (foreseeably in `core/tests` and `cli/tests`) are run when the [test workflow](https://github.com/seedcase-project/.github/blob/main/.github/workflows/test.yml) runs.

You can run the built-in unittests with e.g. `poetry run python -m unittest discover -s sprout/core/tests`(, but we will be moving to pytest).

**Comment by lwjohnst86** [comment]
Using pytest solves this issue 😌
