### ISSUE TITLE
Investigate what gets added to this repo

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/.github#3]

**Comment by signekb** [comment]
We have discussed three issue templates to be added: 
- user story (#2 - already existed in seedcase-project repo) 
- feature request 
- bug report

**Comment by lwjohnst86** [comment]
I think we've investigated this enough. Closing!

**Comment by signekb** [comment]
@lwjohnst86 I haven't looked into it that much, but I guess you might have? Should we write in the README what this repo covers?

**Comment by lwjohnst86** [comment]
@signekb Yea, I think we've mostly added the files that are able to be added to this repo. We also should create a organizational README ([described here](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile)). I'll make an issue, but I don't think we need to do it in this iteration.
