### ISSUE TITLE
Include the British English spellcheck extension

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/.github#35]
Not use if we want to decide on using British English or US spelling of words. There's an extension for including the British English spelling: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-british-english

**Comment by K-Beicher** [comment]
In order to have both the UK and the US spelling the following settings should be implemented for CSpell.

"cSpell.language": "en,en-GB",

@lwjohnst86 can this be shared via the .Github repo, or should we set it individually?

**Comment by lwjohnst86** [comment]
This could definitely be put into the settings in `.github`!
