### ISSUE TITLE
Create PR template for documentation and non-code

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/.github#5]
Brainstorm some ideas here.

For instance, include:

- Checklist for "Re-rendered website"

**Comment by K-Beicher** [comment]
Just a quick question @lwjohnst86, neither Signe nor I have done a re-rendering of the website when submitting a PR for new documentation.  Which steps are you thinking should be included here?

**Comment by lwjohnst86** [comment]
I've seen Signe rendering the website while writing content. Do you mean to re-create the website online? That is done automatically, no steps are needed here. I think the only step to include on the template is to "render the website on your own computer to confirm the changes haven't broken anything" :stuck_out_tongue:
